version: 2.1

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      # Lint the Dockerfile
      - run:
          name: Lint Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG}" .
